### ISSUE TITLE
Compilation Failed

### ISSUE THREAD

**Issue by akki777** [Kotlin/kotlin-koans#150]
The `Compare with Answer` in the Task Description window shows "Contents are identical". Still when I "Check Task" in the Task Description window, I get **Compilation Failed**. 

This is happening in _IntelliJ 2017.3.4_ as well as _Android Studio 3.1.2_ .
The "Lesson 1 - Task 1 (hello World.kt)" works fine. but afterwards this issue occurs.
It says I have issues in other lessons like "Generics Task 1" and in tests file also.

**Comment by jimandreas** [comment]
I just tried the EduTools JetBrains plugin on  IntelliJ IDEA 2018.1.1 and it seems to work OK.
However I find it critical to look at the unit tests as I work on the solution to the koan - and I don't see where you can get a view of the unit test in the plugin.   I recommend pulling in the repo to a folder on your hard drive by:
 
`File->New->Project from Version Control->Git` and then download the Koans repo:

https://github.com/Kotlin/kotlin-koans

Then you can run the Junit tests in the Project `kotlin-koans/test` hierarchy as you do the work.   Just right click on the tests (Windows) and run or debug them.  The IDE gives you lots of useful feedback about type information, runtime library help, and links to the documentation.   Don't forget the links to the documentation as pointed out in the 0 Hello World entry (click on doc reference and on Windows hit Control-Q).   Also use "Control B" to pop to declarations and Control-Alt-leftArrow to pop back to your work.   Enjoy!!

**Comment by akki777** [comment]
I realised recently @haposik has also raised the same issue (with the screenshot).
https://github.com/Kotlin/kotlin-koans/issues/148. Please look at it to get a clear view.

**Comment by jimandreas** [comment]
You might try running the Junit test manually and look for details on the build errors.

Try switching to the Project Files view in the Project tool window, then navigate to lesson2 / task6 / lesson2-task6_test.   Then you can run the test manually as indicated in the screenshot below.   The View / Tool Windows / { Messages and Build } windows might have hints about the compiler complaints.

![koansmanually](https://user-images.githubusercontent.com/15666465/39684997-ec2715fe-51bf-11e8-9805-399c2e92ac1c.PNG)

To switch back to plug in mode, select "Course" in the project window.

**Comment by akki777** [comment]
I find this as a bug..so this *should be solved*, instead of finding a workaround.

**Comment by jimandreas** [comment]
What compiler errors are you seeing?   This information should be in the  View / Tool Windows / { Messages and Build } windows as you are seeing a compile errors.   If you post your compile errors then the IntelliJ people will have clues about the problem.

**Comment by akki777** [comment]
Following is the Error in `Problems` window.
<img width="847" alt="screen shot 2018-05-08 at 6 43 57 pm" src="https://user-images.githubusercontent.com/10670135/39759299-f7e64b7c-52ef-11e8-9800-bc155ae770eb.png">

This issue also has the screenshot -> https://github.com/Kotlin/kotlin-koans/issues/148

**Comment by jimandreas** [comment]
The lesson6 / task1 problem (Generics) is the last problem in project.  It doesn't compile until you get the whole solution right.   I confess I had to peek at the solution.   Spoiler - my modified solution is below - if you paste this solution over the top of the:

`fun partitionTo() = TODO()`

line in the problem - this should compile and solve the problem.   The solution is quite tricky - the syntax has to be exactly correct before the compile errors disappear.   TYP = type of items in the collections, and COLL = the "flavor" (HashSet or ArrayList in this case) of the collection.

```
fun <TYP, COLL: MutableCollection<TYP>> Collection<TYP>.partitionTo(
        list1: COLL, list2: COLL, predicate: (TYP) -> Boolean)
        : Pair<COLL, COLL> {
    for (item in this) {
        if (predicate(item)) {
            list1.add(item)
        } else {
            list2.add(item)
        }
    }
    return Pair(list1, list2)
}
```

**Comment by jimandreas** [comment]
Sorry that I cannot help you.  Can another reader attempt to provide help to @akki777 ?

**Comment by stevematdavies** [comment]
I have the same issue with all the Koans. I'm trying to get it running on gradle with Java 10, but I'm beginning to suspect this is the issue. Is there anywhere we can see the supported JVM numbers?

**Comment by akki777** [comment]
I guess no one from the team cares to look into this or other issues. @svtk

**Comment by svtk** [comment]
Many things here. 
About the initial problem with the Edu plugin. I've added a new issue https://youtrack.jetbrains.com/issue/EDU-1500, please provide more details there. That looks like a bug, but we need more details of how exactly to reproduce it (which versions of everything etc).

Another issue with tests: https://youtrack.jetbrains.com/issue/EDU-1005.

About Java versions: should work with all Java versions, but I can't guarantee that's not another bug with Java 10. @stevematdavies, if you could provide more details in the issue, we can check.

Sorry if I missed something. Edu plugin issues should be discussed in the tracker. So if other problems occur, please provide the details there. Thanks!

**Comment by ryanlijianchang** [comment]
I got this problem also when I work on Lesson 1/Task2.kt, when I click Check, it tips compilation failed.

can anyone help me ? note: I work on android studio V3.4.1.

![](https://i.imgur.com/H73QFw2.png)

**Comment by xiaowx2010** [comment]
> I got this problem also when I work on Lesson 1/Task2.kt, when I click Check, it tips compilation failed.
> 
> can anyone help me ? note: I work on android studio V3.4.1, and my PC is windows 7
> 
> ![](https://camo.githubusercontent.com/bd9ea521726801b9214565341b4d4bc39bd63188/68747470733a2f2f692e696d6775722e636f6d2f746c59756342472e706e67)
> 
> ![](https://camo.githubusercontent.com/441a49d8ca6103780f28570fda9841c63f7f1c6e/68747470733a2f2f692e696d6775722e636f6d2f483733514677322e706e67)

I have the same problem and my Android Studio version is 3.5.1

**Comment by mictaege** [comment]
> > I got this problem also when I work on Lesson 1/Task2.kt, when I click Check, it tips compilation failed.
> > can anyone help me ? note: I work on android studio V3.4.1, and my PC is windows 7
> > ![](https://camo.githubusercontent.com/bd9ea521726801b9214565341b4d4bc39bd63188/68747470733a2f2f692e696d6775722e636f6d2f746c59756342472e706e67)
> > ![](https://camo.githubusercontent.com/441a49d8ca6103780f28570fda9841c63f7f1c6e/68747470733a2f2f692e696d6775722e636f6d2f483733514677322e706e67)
> 
> I have the same problem and my Android Studio version is 3.5.1

Exactly the same with IntelliJ IDEA 2019.3.4, latest Kotlin and EduTools plugins and jdk1.8.0_191
